name: PHP Composer

on:
  push:
    branches: [ "main", "[0-9]+.[0-9]+.[0-9]+.*", "github-actions" ]
  pull_request:
    branches: [ "main", "[0-9]+.[0-9]+.[0-9]+.*", "github-actions" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '5.4', '5.5', '5.6', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]
    name: PHP ${{ matrix.php }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP environment
      uses: nanasess/setup-php@v3.3.2
      with:
        php-version: ${{ matrix.php }}

    - name: Use Composer 2.2 LTS
      run: composer self-update --2.2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
